FROM node:22-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy pnpm-lock.yaml and package.json
COPY pnpm-lock.yaml package.json tsconfig.build.json tsconfig.json ./

COPY . .

# Install dependencies
RUN pnpm install --frozen-lockfile
ADD . ./

# Build TypeScript files
RUN pnpm build
