include:
  - docker/database.yml
  - docker/logs.yml
  - docker/monitoring.yml
  - docker/edge.yml
  - docker/service.yml
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    command: [ ]
    volumes:
      - node_modules:/app/node_modules
    deploy:
      mode: replicated
      replicas: 0

volumes:
  node_modules:
    driver: local