FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache git

# Install pnpm
RUN npm install -g pnpm pm2

# Copy only relevant files and folders for build context
COPY .npmrc pnpm-workspace.yaml pnpm-lock.yaml package.json tsconfig.build.json tsconfig.json ./
COPY libs ./libs
COPY packages ./packages
COPY scripts ./scripts

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Build TypeScript files
RUN pnpm build
#RUN pnpm test
