services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    volumes:
      - 'prometheus-config:/etc/prometheus'
      - 'prometheus-data:/prometheus'
    labels:
      co.elastic.logs/enabled: "false"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - '~/alertmanager.yml:/alertmanager/alertmanager.yml'
    ports:
      - '9093:9093'
    depends_on:
      - prometheus
    labels:
      co.elastic.logs/enabled: "false"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - '9091:9091'
    depends_on:
      - prometheus
    labels:
      co.elastic.logs/enabled: "false"

volumes:
  prometheus-config:
    driver: local
  prometheus-data:
    driver: local