services:
  one:
    image: "project-one:latest"
    build:
      dockerfile: packages/one/Dockerfile
      context: ..
      tags:
        - "latest"
        - "0.0.1"
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true

  two:
    build:
      dockerfile: packages/two/Dockerfile
      context: ..
      tags:
        - "latest"
        - "0.0.1"
    labels:
      co.elastic.logs/enabled: "true"
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.expand_keys: true
